version: '2'

services:
  helloproxy:
    image: klmcwhirter/hellonginx
    ports:
      - "8080:80"
    volumes:
      - ./etc/hello.conf:/etc/nginx/nginx.conf
    networks:
      - helloweb

  hellowebapi:
    image: klmcwhirter/hellowebapi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - HELLODOCKER=true
    networks:
        - helloweb

networks:
  helloweb:
    driver: bridge
